Bugfix/do not raise exception on flusher stop
logtail/logtail-python pull request #19
Opened 2023-11-13 20:13 UTC by Nnonexistent

Fixes #18

2023-12-04 23:02 UTC, curusarn requested changes
Thanks a lot for the PR! Sorry for the wait! 

Left some minor comments. Otherwise looks good!

2023-12-04 23:02 UTC, curusarn commented on tests/test_flusher.py
> +        self.assertFalse(fw.is_alive())
Same here:
```suggestion
        self.assertFalse(fw.should_run)
```

2023-12-04 23:02 UTC, curusarn approved these changes

2023-12-04 23:10 UTC, curusarn commented on tests/test_flusher.py
> +
```suggestion

# test relies on overriding excepthook which is available from 3.8+
@pytest.mark.skipif(sys.version_info <= (3, 7))
```

2023-12-04 23:12 UTC, curusarn commented on tests/test_flusher.py
> +@pytest.mark.skipif(sys.version_info <= (3, 7))
```suggestion
    # test relies on overriding excepthook which is available from 3.8+
    @pytest.mark.skipif(sys.version_info <= (3, 7))
```

2023-12-04 23:17 UTC, curusarn commented on logtail/flusher.py
> +
```suggestion

import sys
```

2023-12-04 23:22 UTC, curusarn commented on logtail/flusher.py
>  import sys
```suggestion

```

2023-12-05 14:06 UTC, Nnonexistent commented
@curusarn I see you've already edited code to your preferences - thanks!

I, hopefully, fixed the skip condition for 3.7 python - pls run the workflow to verify it.

If you need something else done in this PR, please let me know

2023-12-05 15:08 UTC, curusarn commented
Thanks! 

I ran the workflow, and it passed. Everything looks good.

I will merge and release a version soon!

2023-12-13 15:16 UTC, merged

2023-12-13 15:34 UTC, PetrHeinz commented
@Nnonexistent Thank you for the contribution, I just released it as [v0.2.8](https://github.com/logtail/logtail-python/releases/tag/v0.2.8)